### PR TITLE
i just noticed it

### PR DESCRIPTION
**Pull request by ctf0**
we also need to update this or we are still going to get error for the damn es2015 preset.

### CODE REVIEW

**Comment by gocanto** [comment]
Are you sure we do not need to update something else?

**Comment by ctf0** [comment]
i know exactly what u mean, i  focken hate bable.

and yes this is the last of them, i apologize for the mess.

**Comment by gocanto** [comment]
Let me know whether u need a new release of it.

thanks for ur help :)

**Comment by ctf0** [comment]
yes, otherwise users will get an error if they dont have the es2015 preset installed

**Comment by gocanto** [comment]
done

**Pull request merged**
