### PR TITLE
fix Cannot assign to read only property 'exports' of object '#<Object>'

### PR DESCRIPTION
**Pull request by ctf0**
according to https://github.com/webpack/webpack/issues/4039#issuecomment-273804003, now the issue is gone 🎉

### CODE REVIEW

**Comment by gocanto** [comment]
what's the benefit of it? :)

**Comment by ctf0** [comment]
u dont get the error in the console anymore which basically stops the lib from working, nor u need to add the `preset: ['env']` in the webpack config "at least not in laravel mix"

**Comment by gocanto** [comment]
Ok, thanks :)

**Comment by ctf0** [comment]
@gocanto can u push a new release with the new changes ? 🏅

**Comment by gocanto** [comment]
Done. `1.0.9` is out. Thanks :)

**Pull request merged**
